### PR TITLE
Galene v2

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
```
51735 INFO DEBUG - + sudo -u galene CGO_ENABLED=0 /opt/goenv/versions/1.19.5/bin/go build '-ldflags=-s -w' -o /var/www/galene/live/
51736 INFO DEBUG - failed to initialize build cache at /home/galene/.cache/go-build: mkdir /home/galene: permission denied
```

Hmyeah I need to fix that issue with the user's home in the core I think

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
