### PR TITLE
Upgrade

### LINKED ISSUE #64: LDAP integration
The upcoming version 0.5 of Galene will have support for external authorisation servers.  A working but slightly incomplete version of that code is in the branch "auth" of the Galene repository.  It is described here: https://lists.galene.org/galene/87tugzwezl.wl-jch@irif.fr

It would certainly be desirable if that support could be used to better integrate Galene with Yunohost.  Other people who have expressed interest in working on an LDAP authorisation server for Galene are @erdnaxe and @georgesk.  Please see also the discussion at https://github.com/jech/galene/pull/106.

### LINKED ISSUE #79: Passwords with quotes breaks the JSON
### Describe the bug

When installing the application, if the password contains quotes, it breaks the configuration json file (`/home/yunohost.app/galene/groups/GROUP.json`)

- Install Galene using a password containing quotes (like `1"2"3"4"5`)
- After the installation, you should not be able to join the group filled during the installation
- Also you should get a broken JSON in `/home/yunohost.app/galene/groups/GROUP.json` due to the quotes not being escaped

### Logs

```
mars 13 21:31:51 domain.tld systemd[1]: Started Galène: videoconferencing server.
mars 13 21:31:51 domain.tld galene[23076]: 2022/03/13 21:31:51 Starting built-in TURN server on XX.XX.XX.XX:1195
mars 13 21:31:51 domain.tld galene[23076]: 2022/03/13 21:31:51 data/config.json: invalid character '<character here>' after object key:value pair
mars 13 21:31:51 domain.tld galene[23076]: 2022/03/13 21:31:51 Group file /home/yunohost.app/galene/groups/skeptikon.json: invalid character '<character here>' after object key:value pair
mars 13 21:31:51 domain.tld galene[23076]: 2022/03/13 21:31:51 Relay test successful in 30.98294ms, RTT = 264.613µs
mars 13 21:37:22 domain.tld galene[23076]: 2022/03/13 21:37:22 group.Add: invalid character '<character here>' after object key:value pair
```

Thanks for your work! :pray:

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #64*
- *Fix #79*

## Solution

- *Apply last example_ynh*
- *Implement autoupdater and switch to building with Go*
- *Implement LDAP authentication*
- *Tweak the group page*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by ericgaspar** [comment]
There is 3 roles in Galène: `op`, `presenter`, `other`. Right now every YunoHost user connecting with LDAP is given `presenter` role . No `op` (administrator) role is assigned. I don’t know if it is possible to set the choosen admin during install as `op` for LDAP connection.

**Comment by yalh76** [comment]
> There is 3 roles in Galène: `op`, `presenter`, `other`. Right now every YunoHost user connecting with LDAP is given `presenter` role . No `op` (administrator) role is assigned. I don’t know if it is possible to set the choosen admin during install as `op` for LDAP connection.

I don't know well galene but I will took a look

**Comment by yalh76** [comment]
> There is 3 roles in Galène: `op`, `presenter`, `other`. Right now every YunoHost user connecting with LDAP is given `presenter` role . No `op` (administrator) role is assigned. I don’t know if it is possible to set the choosen admin during install as `op` for LDAP connection.

When reading the readme: https://github.com/jech/galene-ldap, I don't see any way to specify the role depending of a yunohost ldap group/permission ...

**Comment by ericgaspar** [comment]
> > There is 3 roles in Galène: `op`, `presenter`, `other`. Right now every YunoHost user connecting with LDAP is given `presenter` role . No `op` (administrator) role is assigned. I don’t know if it is possible to set the choosen admin during install as `op` for LDAP connection.
> 
> When reading the readme: https://github.com/jech/galene-ldap, I don't see any way to specify the role depending of a yunohost ldap group/permission ...

Maybe @jech as more in depth infos...

**Comment by jech** [comment]
The authorisation server sets the permissions here:  <https://github.com/jech/galene-ldap/blob/d0ffa0eadcf17150450d0222c07a2f8cf4e28d7e/token.go#L107>.  In the current version of the code, it is set to just "present".  If you wish to give the user full rights, you should set it to the list `["op", "present", "record"]`.

It's not obvious to me how to decide what rights are given to a user: should all LDAP users have full permissions, or should there be a field somewhere in LDAP that specifies the Galene permissions, or should there be a field in LDAP to specify which users get full permissions?  I'll be happy to change the code if @ericgaspar and the community decide what is the right behaviour.

**Comment by yalh76** [comment]
> It's not obvious to me how to decide what rights are given to a user: should all LDAP users have full permissions, or should there be a field somewhere in LDAP that specifies the Galene permissions, or should there be a field in LDAP to specify which users get full permissions? I'll be happy to change the code if @ericgaspar and the community decide what is the right behaviour.

From my point of view, the most flexible would be to be able to do a mapping from an ldap group to a galene permission, we made something similar on kimai2:

https://github.com/YunoHost-Apps/kimai2_ynh/blob/ef7f7d388e1e2abbe7789b9a9e93230b0f14262a/conf/local.yaml#L120-L164

Roles in kimai2 are like permissions in galene, 3 levels of role: `ROLE_TEAMLEAD, ROLE_ADMIN, ROLE_SUPER_ADMIN`
we created some groups in ldap like `galene.admin` and affecting the permission `op`


We could have something like:
groupname-ldap.json:
``` 
{
 	"description": "YunoHost User Group",
	"public": true,
	"authServer": "https://__DOMAIN__/auth/",
	"authKeys": [
		__KEY__
	],
	"authPermissions": [
		{
			"galene.admin":"op",
			"galene.manager":"presenter",
			"galene.secretary":"record",
		}
	]
}

```

and
galene-ldap.json
```
{
	"httpAddress": "127.0.0.1:__LDAP_PORT__",
	"ldapServer": "ldap://localhost:389",
	"ldapBase": "ou=users,dc=yunohost,dc=org",
	"key": __KEY__,
	"groups": ["YunoHost_Users"],
	"insecure": true,
	"ldapGroupBase": "ou=permission, dc=yunohost, dc=org"
}

```

**Comment by jech** [comment]
I'd be glad to accept a pull request that implements something like what @yalh76 suggests.

The interaction with the LDAP server happens in the function `ldapVerify` here https://github.com/jech/galene-ldap/blob/master/ldap.go#L34.  It should be easy to adapt to your needs.

**Comment by yalh76** [comment]
> I'd be glad to accept a pull request that implements something like what @yalh76 suggests. The interaction with the LDAP server happens in the function `ldapVerify` here https://github.com/jech/galene-ldap/blob/master/ldap.go#L34. It should be easy to adapt to your needs.
> 
> I expect the main issue to be how this is configured. My preference with security is to be as simple as possible, and that's why Galene only exposes three roles (op, presenter, other) while the underlying protocol supports 4 orthogonal permissions and therefore 16 possible roles. It's up to you guys, I'll be glad to accept whatever syntax you believe meets your needs.

@jech : I can try but for now I've no knowledge of go language, but i'm pretty good at copy/paste

@ericgaspar : do we merge or do we wait to have all yunohost / galene permissions implemented ?

**Comment by jech** [comment]
> I can try but for now I've no knowledge of go language

I'll review your code carefully, then, and make loads of snarky comments ;-)

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@ericgaspar did we merge that PR for now ?

**Comment by jech** [comment]
Cool.

Please let me know if you feel that other features are needed, either in Galene itself or in the authorisation server, to make the integration as smooth as possible, I'm open to adding features even if they're only used by Yunohost.

**Comment by yalh76** [comment]
> Cool.
> 
> Please let me know if you feel that other features are needed, either in Galene itself or in the authorisation server, to make the integration as smooth as possible, I'm open to adding features even if they're only used by Yunohost.

Yes I have one:
I've done that in the YunoHost package:

https://github.com/YunoHost-Apps/galene_ynh/blob/ed1506fa3eb56358fecb06d832c9684acbf682d9/scripts/install#L114

To make the top left header been a link to go back to the main page when you are in a group page, I think, it would be useffull for all

**Comment by jech** [comment]
> onclick=\"location.href=window.location.origin\"

Why the origin rather than just "location.href='/'"?

**Comment by pp-r** [comment]
Hello,

I can't update from 0.6.1~ynh1 to 0.6.1~ynh2 because '/opt/yunohost/galene/build/static/': No such file or directory

>2022-10-14 17:53:19,183: DEBUG - + '[' UPGRADE_PACKAGE == UPGRADE_APP ']'
>2022-10-14 17:53:19,183: DEBUG - + mkdir -p /opt/yunohost/galene/live/data
>2022-10-14 17:53:19,187: DEBUG - + mkdir -p /opt/yunohost/galene/live_ldap/data
>2022-10-14 17:53:19,191: DEBUG - + ynh_secure_remove --file=/opt/yunohost/galene/live/static/
>2022-10-14 17:53:19,235: DEBUG - + cp -r /opt/yunohost/galene/build/static/ /opt/yunohost/galene/live/
>2022-10-14 17:53:19,240: WARNING - cp: cannot stat '/opt/yunohost/galene/build/static/': No such file or directory
>2022-10-14 17:53:19,243: DEBUG - + ynh_exit_properly
>2022-10-14 17:53:19,751: DEBUG - + ynh_clean_setup
>2022-10-14 17:53:19,752: DEBUG - + ynh_restore_upgradebackup
>2022-10-14 17:53:19,752: DEBUG - + ynh_print_err '--message=Upgrade failed.'
>2022-10-14 17:53:19,774: DEBUG - + ynh_print_log '[Error] Upgrade failed.'
>2022-10-14 17:53:19,775: DEBUG - + echo -e '[Error] Upgrade failed.'
>2022-10-14 17:53:19,775: DEBUG - + local app_bck=galene
>2022-10-14 17:53:19,775: DEBUG - + NO_BACKUP_UPGRADE=0
>2022-10-14 17:53:19,775: DEBUG - + ynh_backup_archive_exists galene-pre-upgrade2
>2022-10-14 17:53:19,776: WARNING - [Error] Upgrade failed.

Full log is here :
https://paste.yunohost.org/raw/ecotudepap

Tell me if i should do something on my side if it could helps.

**Comment by yalh76** [comment]
> > onclick="location.href=window.location.origin"
> 
> Why the origin rather than `"location.href='/'"`? What's the desired behaviour if there's a link to a Galene group on a web page unrelated to Galene?

just because the origin seems more precise that `href=/`
https://devstory.net/12401/javascript-location
but maybe it's the same ...

**Comment by yalh76** [comment]
> Hello,
> 
> I can't update from 0.6.1 ynh1 to 0.6.1 ynh2 because '/opt/yunohost/galene/build/static/': No such file or directory
> 
> > 2022-10-14 17:53:19,183: DEBUG - + '[' UPGRADE_PACKAGE == UPGRADE_APP ']'
> > 2022-10-14 17:53:19,183: DEBUG - + mkdir -p /opt/yunohost/galene/live/data
> > 2022-10-14 17:53:19,187: DEBUG - + mkdir -p /opt/yunohost/galene/live_ldap/data
> > 2022-10-14 17:53:19,191: DEBUG - + ynh_secure_remove --file=/opt/yunohost/galene/live/static/
> > 2022-10-14 17:53:19,235: DEBUG - + cp -r /opt/yunohost/galene/build/static/ /opt/yunohost/galene/live/
> > 2022-10-14 17:53:19,240: WARNING - cp: cannot stat '/opt/yunohost/galene/build/static/': No such file or directory
> > 2022-10-14 17:53:19,243: DEBUG - + ynh_exit_properly
> > 2022-10-14 17:53:19,751: DEBUG - + ynh_clean_setup
> > 2022-10-14 17:53:19,752: DEBUG - + ynh_restore_upgradebackup
> > 2022-10-14 17:53:19,752: DEBUG - + ynh_print_err '--message=Upgrade failed.'
> > 2022-10-14 17:53:19,774: DEBUG - + ynh_print_log '[Error] Upgrade failed.'
> > 2022-10-14 17:53:19,775: DEBUG - + echo -e '[Error] Upgrade failed.'
> > 2022-10-14 17:53:19,775: DEBUG - + local app_bck=galene
> > 2022-10-14 17:53:19,775: DEBUG - + NO_BACKUP_UPGRADE=0
> > 2022-10-14 17:53:19,775: DEBUG - + ynh_backup_archive_exists galene-pre-upgrade2
> > 2022-10-14 17:53:19,776: WARNING - [Error] Upgrade failed.
> 
> Full log is here : https://paste.yunohost.org/raw/ecotudepap
> 
> Before open an issue, tell me if i should do something on my side if it could helps to resolve.

should be fixed by #96

**Pull request merged**
