### PR TITLE
Fix upgrade from 0.6.1 ynh1

### PR DESCRIPTION
**Pull request by yalh76**
## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by pp-r** [comment]
Upgrade from 0.6.1-ynh1 to 0.6.1-ynh4 works :-)
Many thanks !

**Comment by pp-r** [comment]
Hello,

Service `galene_ldap` don't start and the diagnosis complain about it.
I share the log : https://paste.yunohost.org/qerukovuxo

**Comment by ericgaspar** [comment]
@ppr Please read my previous comment: https://github.com/YunoHost-Apps/galene_ynh/issues/98#issuecomment-1281908258

**Comment by pp-r** [comment]
I've remove and reinstall and it works ... sorry for the inconvenience

**Pull request merged**
